runtime: python37
# runtime_config:
#   python_version: 3
# env: flex
# entrypoint: gunicorn -b :$PORT main:app

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

# readiness_check:
#   path: "/readiness_check"
#   check_interval_sec: 10
#   timeout_sec: 5
#   failure_threshold: 2
#   success_threshold: 2
#   app_start_timeout_sec: 1800

# manual_scaling:
#   instances: 1